# Generated by Django 4.2.2 on 2023-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='jobs/1.svg', null=True, upload_to='jobs/%d-%m-%Y'),
        ),
    ]
